const all_task_data = [
  {
    id: 1,
    company: "ShopEase",
    title: "Fix Mobile Button Issue",
    description: "Debug using Chrome DevTools, check for overlapping elements",
    deadline: "21 March 2025",
    completed: true,
    completeAT: null,
  },
  {
    id: 2,
    company: "CloudSync",
    title: "Add Dark Mode",
    description: "Store the user's preference in localStorage, update CSS variables",
    deadline: "21 March 2025",
    completed: false,
    completeAT: null,
  },
  {
    id: 3,
    company: "SwiftPay",
    title: "Optimize Home page",
    description: "Debug using Chrome DevTools, check for overlapping elements",
    deadline: "21 March 2025",
    completed: false,
    completeAT: null,
  },
  {
    id: 4,
    company: "Meta",
    title: "Add new emoji 😊",
    description: "Debug using Chrome DevTools, check for overlapping elements",
    deadline: "21 March 2025",
    completed: false,
    completeAT: null,
  },
  {
    id: 5,
    company: "Google LLC",
    title: "Integrate OpenAI API",
    description: "Debug using Chrome DevTools, check for overlapping elements",
    deadline: "21 March 2025",
    completed: false,
    completeAT: null,
  },
  {
    id: 6,
    company: "Glassdoor",
    title: "Improve Job searching",
    description: "Debug using Chrome DevTools, check for overlapping elements",
    deadline: "21 March 2025",
    completed: false,
    completeAT: null,
  },
];


